use_frameworks!

platform :ios, '10.0'

target 'JQ_bundle_test_framework_Example' do
  pod 'JQ_bundle_test_framework', :path => '../'

  target 'JQ_bundle_test_framework_Tests' do
    inherit! :search_paths

    
  end
end
